server {
    listen 80;
    server_name chat.lipagas.co influence.deepintelgroup.com builder.lipagas.co flow.lipagas.co;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name chat.lipagas.co influence.deepintelgroup.com;
    
    ssl_certificate /etc/letsencrypt/live/chat.lipagas.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.lipagas.co/privkey.pem;
    
    location / {
        proxy_pass http://rails:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name builder.lipagas.co;
    
    ssl_certificate /etc/letsencrypt/live/builder.lipagas.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/builder.lipagas.co/privkey.pem;

    location / {
        proxy_pass http://typebot-builder:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name flow.lipagas.co;
    
    ssl_certificate /etc/letsencrypt/live/flow.lipagas.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flow.lipagas.co/privkey.pem;

    location /meta-webhook {
        proxy_pass http://lipagas-bridge:4000/meta-webhook;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /trigger-mpesa {
        proxy_pass http://lipagas-bridge:4000/trigger-mpesa;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /parse-cart {
        proxy_pass http://lipagas-bridge:4000/parse-cart;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://typebot-viewer:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
